key_bindings:
  - { key: F, mods: Control, action: ToggleViMode }
window:
  opacity: 1
font:
  normal:
    family: RobotoMono Nerd Font
    style: Regular

  bold:
    family: RobotoMono Nerd Font
    style: Bold

  italic:
    family: RobotoMono Nerd Font
    style: Italic

  bold_italic:
    family: RobotoMono Nerd Font
    style: Bold Italic
  size: 11

color_schemes:
  github_light: &github_light
    primary:
      background: "0xffffff"
      foreground: "0x1F2328"

    # Cursor colors
    #
    # These will only be used when the `custom_cursor_colors` field is set to `true`.
    cursor:
      text: "0xffffff"
      cursor: "0x1f2328"

    # Normal colors
    normal:
      black: "0x24292f"
      red: "0xcf222e"
      green: "0x116329"
      yellow: "0x4d2d00"
      blue: "0x0969da"
      magenta: "0x8250df"
      cyan: "0x1b7c83"
      white: "0x6e7781"

    # Bright colors
    bright:
      black: "0x57606a"
      red: "0xa40e26"
      green: "0x1a7f37"
      yellow: "0x633c01"
      blue: "0x218bff"
      magenta: "0x8250df"
      cyan: "0x1b7c83"
      white: "0x6e7781"

  github_dark: &github_dark
    primary:
      background: "0x30363d"
      foreground: "0xe6edf3"

    # Cursor colors
    #
    # These will only be used when the `custom_cursor_colors` field is set to `true`.
    cursor:
      text: "0x30363d"
      cursor: "0xe6edf3"

    # Normal colors
    normal:
      black: "0x484f58"
      red: "0xff7b72"
      green: "0x3fb950"
      yellow: "0xd29922"
      blue: "0x58a6ff"
      magenta: "0xbc8cff"
      cyan: "0x39c5cf"
      white: "0xb1bac4"

    # Bright colors
    bright:
      black: "0x6e7681"
      red: "0xffa198"
      green: "0x56d364"
      yellow: "0xe3b341"
      blue: "0x79c0ff"
      magenta: "0xbc8cff"
      cyan: "0x39c5cf"
      white: "0xb1bac4"

  latte: &latte # Default colors
    primary:
      background: "#eff1f5" # base
      # background: '#ffffff' # base
      foreground: "#4c4f69" # text
      # Bright and dim foreground colors
      dim_foreground: "#4c4f69" # text
      bright_foreground: "#4c4f69" # text

    # Cursor colors
    cursor:
      text: "#eff1f5" # base
      cursor: "#dc8a78" # rosewater
    vi_mode_cursor:
      text: "#eff1f5" # base
      cursor: "#7287fd" # lavender

    # Search colors
    search:
      matches:
        foreground: "#eff1f5" # base
        background: "#6c6f85" # subtext0
      focused_match:
        foreground: "#eff1f5" # base
        background: "#40a02b" # green
    footer_bar:
      foreground: "#eff1f5" # base
      background: "#6c6f85" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#eff1f5" # base
        background: "#df8e1d" # yellow
      end:
        foreground: "#eff1f5" # base
        background: "#6c6f85" # subtext0

    # Selection colors
    selection:
      text: "#eff1f5" # base
      background: "#dc8a78" # rosewater

    # Normal colors
    normal:
      black: "#4C4F69" # text
      red: "#D20F39" # red
      green: "#40A02B" # green
      yellow: "#DF8E1D" # yellow
      blue: "#1E66F5" # blue
      magenta: "#EA76CB" # pink
      cyan: "#179299" # teal
      white: "#ACB0BE" # surface2

    # Bright colors
    bright:
      black: "#4C4F69" # text
      red: "#D20F39" # red
      green: "#40A02B" # green
      yellow: "#DF8E1D" # yellow
      blue: "#1E66F5" # blue
      magenta: "#EA76CB" # pink
      cyan: "#179299" # teal
      white: "#ACB0BE" # surface2

    # Dim colors
    dim:
      black: "#4C4F69" # text
      red: "#D20F39" # red
      green: "#40A02B" # green
      yellow: "#DF8E1D" # yellow
      blue: "#1E66F5" # blue
      magenta: "#EA76CB" # pink
      cyan: "#179299" # teal
      white: "#ACB0BE" # surface2

  frappe: &frappe # Default colors
    primary:
      background: "#303446" # base
      foreground: "#c6d0f5" # text
      # Bright and dim foreground colors
      dim_foreground: "#c6d0f5" # text
      bright_foreground: "#c6d0f5" # text

    # Cursor colors
    cursor:
      text: "#303446" # base
      cursor: "#f2d5cf" # rosewater
    vi_mode_cursor:
      text: "#303446" # base
      cursor: "#babbf1" # lavender

    # Search colors
    search:
      matches:
        foreground: "#303446" # base
        background: "#a5adce" # subtext0
      focused_match:
        foreground: "#303446" # base
        background: "#a6d189" # green
    footer_bar:
      foreground: "#303446" # base
      background: "#a5adce" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#303446" # base
        background: "#e5c890" # yellow
      end:
        foreground: "#303446" # base
        background: "#a5adce" # subtext0

    # Selection colors
    selection:
      text: "#303446" # base
      background: "#f2d5cf" # rosewater

    # Normal colors
    normal:
      black: "#51576d" # surface1
      red: "#e78284" # red
      green: "#a6d189" # green
      yellow: "#e5c890" # yellow
      blue: "#8caaee" # blue
      magenta: "#f4b8e4" # pink
      cyan: "#81c8be" # teal
      white: "#b5bfe2" # subtext1

    # Bright colors
    bright:
      black: "#51576d" # surface1
      red: "#e78284" # red
      green: "#a6d189" # green
      yellow: "#e5c890" # yellow
      blue: "#8caaee" # blue
      magenta: "#f4b8e4" # pink
      cyan: "#81c8be" # teal
      white: "#b5bfe2" # subtext1

    # Dim colors
    dim:
      black: "#51576d" # surface1
      red: "#e78284" # red
      green: "#a6d189" # green
      yellow: "#e5c890" # yellow
      blue: "#8caaee" # blue
      magenta: "#f4b8e4" # pink
      cyan: "#81c8be" # teal
      white: "#b5bfe2" # subtext1

  macchiato: &macchiato # Default colors
    primary:
      background: "#24273a" # base
      foreground: "#cad3f5" # text
      # Bright and dim foreground colors
      dim_foreground: "#cad3f5" # text
      bright_foreground: "#cad3f5" # text

    # Cursor colors
    cursor:
      text: "#24273a" # base
      cursor: "#f4dbd6" # rosewater
    vi_mode_cursor:
      text: "#24273a" # base
      cursor: "#b7bdf8" # lavender

    # Search colors
    search:
      matches:
        foreground: "#24273a" # base
        background: "#a5adcb" # subtext0
      focused_match:
        foreground: "#24273a" # base
        background: "#a6da95" # green
    footer_bar:
      foreground: "#24273a" # base
      background: "#a5adcb" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#24273a" # base
        background: "#eed49f" # yellow
      end:
        foreground: "#24273a" # base
        background: "#a5adcb" # subtext0

    # Selection colors
    selection:
      text: "#24273a" # base
      background: "#f4dbd6" # rosewater

    # Normal colors
    normal:
      black: "#494d64" # surface1
      red: "#ed8796" # red
      green: "#a6da95" # green
      yellow: "#eed49f" # yellow
      blue: "#8aadf4" # blue
      magenta: "#f5bde6" # pink
      cyan: "#8bd5ca" # teal
      white: "#b8c0e0" # subtext1

    # Bright colors
    bright:
      black: "#494d64" # surface1
      red: "#ed8796" # red
      green: "#a6da95" # green
      yellow: "#eed49f" # yellow
      blue: "#8aadf4" # blue
      magenta: "#f5bde6" # pink
      cyan: "#8bd5ca" # teal
      white: "#b8c0e0" # subtext1

    # Dim colors
    dim:
      black: "#494d64" # surface1
      red: "#ed8796" # red
      green: "#a6da95" # green
      yellow: "#eed49f" # yellow
      blue: "#8aadf4" # blue
      magenta: "#f5bde6" # pink
      cyan: "#8bd5ca" # teal
      white: "#b8c0e0" # subtext1

  mocha: &mocha # Default colors
    primary:
      background: "#1e1e2e" # base
      foreground: "#cdd6f4" # text
      # Bright and dim foreground colors
      dim_foreground: "#cdd6f4" # text
      bright_foreground: "#cdd6f4" # text

    # Cursor colors
    cursor:
      text: "#1e1e2e" # base
      cursor: "#f5e0dc" # rosewater
    vi_mode_cursor:
      text: "#1e1e2e" # base
      cursor: "#b4befe" # lavender

    # Search colors
    search:
      matches:
        foreground: "#1e1e2e" # base
        background: "#a6adc8" # subtext0
      focused_match:
        foreground: "#1e1e2e" # base
        background: "#a6e3a1" # green
    footer_bar:
      foreground: "#1e1e2e" # base
      background: "#a6adc8" # subtext0

    # Keyboard regex hints
    hints:
      start:
        foreground: "#1e1e2e" # base
        background: "#f9e2af" # yellow
      end:
        foreground: "#1e1e2e" # base
        background: "#a6adc8" # subtext0

    # Selection colors
    selection:
      text: "#1e1e2e" # base
      background: "#f5e0dc" # rosewater

    # Normal colors
    normal:
      black: "#45475a" # surface1
      red: "#f38ba8" # red
      green: "#a6e3a1" # green
      yellow: "#f9e2af" # yellow
      blue: "#89b4fa" # blue
      magenta: "#f5c2e7" # pink
      cyan: "#94e2d5" # teal
      white: "#bac2de" # subtext1

    # Bright colors
    bright:
      black: "#45475a" # surface1
      red: "#f38ba8" # red
      green: "#a6e3a1" # green
      yellow: "#f9e2af" # yellow
      blue: "#89b4fa" # blue
      magenta: "#f5c2e7" # pink
      cyan: "#94e2d5" # teal
      white: "#bac2de" # subtext1

    # Dim colors
    dim:
      black: "#45475a" # surface1
      red: "#f38ba8" # red
      green: "#a6e3a1" # green
      yellow: "#f9e2af" # yellow
      blue: "#89b4fa" # blue
      magenta: "#f5c2e7" # pink
      cyan: "#94e2d5" # teal
      white: "#bac2de" # subtext1

colors: *github_dark
